# Generated by Django 2.2.5 on 2019-12-20 09:26

from django.db import migrations
import mail_box.models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mailboxuser',
            managers=[
                ('objects', mail_box.models.MailboxUserManager()),
            ],
        ),
    ]
