# Generated by Django 2.2.5 on 2019-12-20 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='addressees_set',
            field=models.ManyToManyField(related_name='incoming_messages_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='letter',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mail_box.Message'),
        ),
        migrations.AddField(
            model_name='letter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letters_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
