# Generated by Django 3.0.1 on 2019-12-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_box', '0002_auto_20191220_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='type',
            field=models.CharField(choices=[('INBOX', 'ВХД'), ('SENT', 'ИСХ')], max_length=5),
        ),
        migrations.AlterField(
            model_name='message',
            name='header',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(max_length=900),
        ),
    ]
